spring:
  redis:
    host: 118.25.11.180
    port: 6379
    password: Wjg50058
    # 连接超时时间（记得添加单位，Duration）
    timeout: 3000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  datasource:
    monitor:
      jdbc-url: jdbc:mysql://10.100.41.220:3957/TCTrainMonitor?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: TCTrainMonitor_local
      password: 2SfohbIN2YWtavZ3AdFgPUU4
      driver-class-name: com.mysql.cj.jdbc.Driver
    skyzen:
      jdbc-url: jdbc:mysql://10.100.156.106:3500/TCTrainSkyZen?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: TCTrainSkyZen_local
      password: VZSaHFGx1zO2ppYwGpSXDek6nLd3zg
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: light
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mapper/*/*.xml
server:
  port: 8080
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
